### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by peakgreg** [FaiezWaseem/CodeEditor#2]
How about building in tabs?

I have used a lot of these different browser based coded editors and I think you are really onto something here. I would love to help you refine it.

**Comment by FaiezWaseem** [comment]
Well i do plan to add tabs , but i am a Little bit stuck with the logic here . And the code is too messy any help would be appreciated.

**Comment by FaiezWaseem** [comment]
@peakgreg Tabs are now added
